SergeiDemyanenko/PlatformaticaQA_02

README.md
Create README.md - Project Coding Convention
=> Create README.md - Project Coding Convention

src/test/java/GroupBugBustersTest.java
Second PR. Forget to change the Test name.
=> Added TestCase By AndreyT

src/test/java/KorikUmanTest.java
=> line correction

src/test/java/GroupJavaBearsTest.java
=> First test created

src/test/java/IrinaBTest.java
=> Irina b ib test

src/test/java/GroupBreakingBadJavaTest.java
Test https://www.lafitness.com/
=> Test Lena D

src/test/java/KorikUmanTest.java
=> Korikuman branch

src/test/java/GroupBugBustersTest.java
=> First commit

src/test/java/GroupBugBustersTest.java
=> test changename

src/test/java/KorikUmanTest.java
test name updated
before test method updated
comments removed
Assertion added to test 1
variable name changed
=> code refactoring

src/test/java/GroupBreakingBadJavaTest.java
=> LenaD test refactoring

src/test/java/IrinaBTest.java
Testing options of opening account on https://us.etrade.com/home
=> IrinaBndTest_https://us.etrade.com

src/test/java/GroupAlmondSkyTest.java
testTatianaChueva() refactoring
=> testTatianaChueva() refactoring

src/test/java/DariaAltukhovaTest.java
Adding a new class `DariaAltukhovaTest` with Selenium Webdriver tests.
=> Daria Altukhova  tests

src/test/java/KorikUmanTest.java
=> Update KorikUmanTest Class to inherit BaseTest Class

src/test/java/EntityTagTest.java
AT_023_Java-Entity-Tag. New created record is added
https://trello.com/c/sev6txMf/179-at023java-entitytag-create-a-new-record
=> Test-Java-Entity-Tag-createRecord

src/test/java/EntityPlaceholderTest.java
https://trello.com/c/hrt1YKjY/211-at040-entityplaceholder-create-a-new-record-and-save
=> AT_040 | Entity > Placeholder: Create new record and save

src/test/java/EntityTagTest.java, src/test/java/utils/TestUtils.java
RF_Java | 026 | Entity > Tag: Save new record as a draft
=> RF_Java | 026 | Entity > Tag: Save new record as a draft

src/test/java/EntityChildRecordsLoopTest.java
Add EntityChildRecordsLoopTest which tests the creation of a Child Records Loop record.
https://trello.com/c/1jSukVXj/22-us074-entity-child-record-loop-create-a-new-record
=> Add EntityChildRecordsLoopTest

src/test/java/EntityChildRecordsLoopTest.java
This PR adds the test method to view created Child Records Loop record
AT_075 | Entity > Child record loop: View created record
https://trello.com/c/EHhRLIzL/277-at075java-entity-child-record-loop-view-created-record
=> View child Records Loop card test method

src/test/java/EntityChildRecordsLoopTest.java
AT_076_Java | Entity >Child record loop: Edit created record
https://trello.com/c/4On7qbl7/336-at076java-entity-child-record-loop-edit-created-record
Also modified existing method which creates a card, so it waits on the table appearance and validate the last card added, instead of the first one.
=> Add testEditChildRecordsLoopCard method

src/test/java/EntityChildRecordsLoopTest.java
Fixed amount selector in a testEditChildRecordsLoopCard method
Deleted ignore
Added method to send keys one by one.
=> ERR_Java |  testEditChildRecordsLoopCard

src/test/java/EntityArithmeticInlineTest.java, src/test/java/EntityBoardViewDraftRecordTest.java, src/test/java/EntityCalendarTest.java
https://trello.com/c/NeRLdNr5/341-at00601java-entity-board-view-draft-record
https://trello.com/c/QZcQWC23/62-us006-entity-board-view-draft-record
https://trello.com/c/OyiLTObb/338-tc00601-java-entity-board-view-draft-record
=> AT_006.01_Java | Entity > Board: View draft record

src/test/java/EntityReferenceValuesDraftTest.java
New class added EntityReferenceValuesDraftTest
https://trello.com/c/hxKzysg8/67-us062-entity-reference-values-create-a-new-record-as-draft
=> AT_062.01_Java | Entity > Reference values : Create a new record as Draft.

src/test/java/EntityAssignTest.java
new test added
https://trello.com/c/pJ39atzo/194-tc06401java-entity-assign-view-record
=> testViewMode added to EntityAssignTest

src/test/java/EntityChildRecordsLoopTest.java
Added new emptyRecycleBinMessage variable.
Added clickRecycleBinIcon method.
Added new testDeletePermanentlyChildRecordsLoopCard method.
=> AT_079_Java | Entity > Child record loop: Delete permanently

src/test/java/EntityChevronSentRecordViaListTest.java
1. validate that created record is placed into the "Sent" folder.
2. validate that created record has the same entered data as was entered before.
=> RF_Java _015 | Entity > Chevron: Sent record via list

src/test/java/EntityBoardViewDraftRecordTest.java
https://trello.com/c/u2Hw6Gtl/777-rfjava-your-title-here
=> refactoring testViewDraftRecord()

src/test/java/EntityChildRecordsLoopTest.java
Added test methods dependencies and removed explicit project utils start
https://trello.com/c/w6r7rdV5/776-rfjava-entity-child-records-loop
=> RF_Java | Entity > Child Records Loop

src/test/java/EntityFieldsTest.java
https://trello.com/c/yhBDZsoK/652-at13401java-entity-fields-search-created-record
Test testSearchCreatedRecord
=> Test testSearchCreatedRecord  was added on Class EntityFieldsTest  

src/test/java/EntityPlaceholderViewAndCancelTest.java
https://trello.com/c/Cdz54kfJ/797-rfjava-entityplaceholderviewandcancel-testcreateandcancel
https://trello.com/c/bgUdsmYh/802-rfjava-entityplaceholderviewandcancel-testviewrecord
https://trello.com/c/yRLpgmls/755-rfjava-entity-placeholder-viewandcanceltest-refactor
=> Refactor: Entity>Placeholder>ViewAndCancelTest

src/test/java/EntityBoardCreateAndSaveTest.java
RF_Java | InputDataAndSaveTest > method addCard https://trello.com/c/JK4rtma1
RF_Java | InputDataAndSaveTest > testInputDataAndSave https://trello.com/c/2QE80div
=> removed addCard method, spaces. Decreased runtime.

src/test/java/EntityFieldsDraftTest.java
Added 5 test for Platformatica Entity: Fields. 
Trello tickets AT_136, AT_137, AT_138, AT_139, and AT_140.
=> Mike kamentsev entity fields draft test
